# Site settings
title: 小一辈无产阶级码农
url: "r9it.com"  
baseurl: "" 
timezone: "Asia/Chongqing"
description: 小一辈无产阶级码农

# Your information
email: yangjian102621@gmail.com
author: blackfox
nickname: 一品鸟人
avatar: "/images/avatar.png"
profile: 独学而无友，则孤陋而寡闻.
index_motto: 学无先后，达着为师.
#twitter_username: twitter_username
github_username:  yangjian102621

#permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

sass:
    style: :compressed
    sass_dir: _sass

# path
categories_path: category/
tags_path: tags/
tags_path: links/

highlighter: rouge
markdown: kramdown
kramdown:
        syntax_highlighter: rouge
        input: GFM
        extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]
